spring:
  profiles.active: test
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
security:
  jwt:
    token:
      secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      expire-length: 3600000

---

spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
    username: ${db-user}
    password: ${db-password}
# db-url=jdbc:mysql://15.165.247.235:8081/kkogkkog?serverTimezone=UTC&characterEncoding=UTF-8; db-user=kkogkkog-prod; db-password=D871A2524DC1391D295CA88CD854A
---

spring:
  config.activate.on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kkogkkog-test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
