name: Backend Test & Build

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test & Build with gradle
        run: ./gradlew build
