name: Backend Test & Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout kkogkkog repository
        uses: actions/checkout@v3

      - name: Set up JDK 11 on runner
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod 744 gradlew

      - name: Test & build with gradle
        run: ./gradlew build
